---
- block:
  - name: Build list of available profile pictures
    shell: ls -1 {{ new_user_random_profile_pictures_path }}/ | grep '{{ new_user_profile_pictures_filter_formats }}'
    register: profile_pictures
    ignore_errors: yes
    delegate_to: localhost
    become: no

  - name: profile_pictures
    debug:
      var: profile_pictures
    when: verbose|bool

  - name: Copy random profile picture in user's Pictures directory
    copy:
      src: "{{ item }}"
      dest: "/Users/{{ new_user_username }}/Pictures/{{ item | basename }}"
      owner: "{{ new_user_username }}"
      mode: 0644
    when: profile_pictures.stdout_lines != []
    with_random_choice: "{{ profile_pictures.stdout_lines }}"
    ignore_errors: yes
    register: random_profile_picture
    become: yes

  - name: random_profile_picture
    debug:
      var:  random_profile_picture
    when: verbose|bool
  # end block
  when:
    - new_user_profile_picture_path == ''
    - new_user_random_profile_picture|bool

- block:
  - name: Copy profile picture in user's Pictures directory
    copy:
      src: "{{ new_user_profile_picture_path }}"
      dest: "/Users/{{ new_user_username }}/Pictures/{{ item | basename }}"
      owner: "{{ new_user_username }}"
      mode: 0644
    ignore_errors: yes
    register: profile_picture
  # end block
  when: new_user_profile_picture_path != ''
  become: yes

- name: Create user profile picture import file.
  template:
    src: picture.dsimport.j2
    dest: "/Library/Caches/{{ username }}.picture.dsimport"
  vars:
    picture_path: "{{ profile_picture.results[0].item|default(random_profile_picture.results[0].item) }}"
    username: "{{ new_user_username }}"
  register: user_profile_picture_created
  when: (profile_picture.changed and profile_picture.results != []) or (random_profile_picture.changed and random_profile_picture.results != [])
  become: yes

- block:
  - name: Clear existing user profile picture
    command: 'dscl . delete /Users/{{ new_user_username }} {{ item }}'
    loop:
      - 'jpegphoto'
      - 'Picture'

  - name: Set the user profile picture.
    command: dsimport "/Library/Caches/{{ new_user_username }}.picture.dsimport" /Local/Default M -u "${ new_user_username }"
    when: random_profile_picture is defined and random_profile_picture.results != []
  # end block
  when: user_profile_picture_created.changed and not user_profile_picture_created.failed
  become: yes
