---
- name: apply random picture if a picture path has not been specified
  block:
  - name: Build list of available profile pictures
    shell: ls -1 {{ new_user_random_profile_pictures_path }}/ | grep -i '{{ new_user_profile_pictures_filter_formats }}'
    register: profile_pictures
    ignore_errors: yes
    delegate_to: localhost
    become: no

  - name: profile_pictures
    debug:
      var: profile_pictures
    when: verbose|bool

  - name: Copy random profile picture in the Pictures directory for the user '{{ new_user_username }}'
    copy:
      src: "{{ new_user_random_profile_pictures_path }}/{{ item }}"
      dest: "/Users/{{ new_user_username }}/Pictures/{{ item | basename }}"
      owner: "{{ new_user_username }}"
      mode: 0644
      group: 'staff'
    when: profile_pictures.stdout_lines != []
    with_random_choice: "{{ profile_pictures.stdout_lines }}"
    ignore_errors: yes
    register: random_profile_picture
    become: yes

  - name: random_profile_picture
    debug:
      var:  random_profile_picture
    when: verbose|bool
  # end block
  when:
    - new_user_profile_picture_path == ''
    - new_user_random_profile_picture|bool

- name: Assign specific picture for the user "{{ new_user_username }}".
  block:
  - name: Copy profile picture in user's Pictures directory
    copy:
      src: "{{ new_user_profile_picture_path }}"
      dest: "/Users/{{ new_user_username }}/Pictures/{{ new_user_profile_picture_path | basename }}"
      owner: "{{ new_user_username }}"
      mode: 0644
      group: 'staff'
    ignore_errors: yes
    register: profile_picture
  # end block
  when: new_user_profile_picture_path | length > 0
  become: yes

- name: profile_picture
  debug:
    var: profile_picture
  when: verbose|bool

- name: Create profile picture import file for the user '{{ username }}'.
  template:
    src: picture.dsimport.j2
    dest: "/Library/Caches/{{ username }}.picture.dsimport"
  vars:
    picture_path: "{{ profile_picture.dest|default(random_profile_picture.results[0].dest) }}"
    username: "{{ new_user_username }}"
  register: user_profile_picture_created
  when:
    - profile_picture is defined or random_profile_picture is defined
    - (profile_picture.dest is defined and profile_picture.dest != []) or (random_profile_picture.results is defined and random_profile_picture.results != [])
  become: yes

- name: user_profile_picture_created
  debug:
    var: user_profile_picture_created
  when: verbose|bool

- name: apply the new picture only of the import file exists and is different than before
  block:
  - name: Clear existing profile picture for the user "{{ new_user_username }}".
    command: 'dscl . delete /Users/{{ new_user_username }} {{ item }}'
    loop:
      - 'jpegphoto'
      - 'Picture'

  - name: Set the profile picture for the user "{{ new_user_username }}".
    command: dsimport "/Library/Caches/{{ new_user_username }}.picture.dsimport" /Local/Default M -u "${ new_user_username }"
  # end block
  when: user_profile_picture_created.changed and not user_profile_picture_created.failed
  become: yes
