---
- name: FATAL - This system is family is {{ ansible_facts['os_family'] }}
  fail:
    msg: "This role is only compatible with macOS"
  when: ansible_facts['os_family'] != 'Darwin'

- block:
  - include_tasks: check-for-exisiting-user.yml
  - debug:
      msg: "Will Skip the configuration of the account for '{{ new_user_username}}' "
    when: new_user_username_already_in_use|default('no')

  - block:
    - include_tasks: create-user.yml

    - block:
      - include_tasks: profile-config.yml

      - include_tasks: generate-ssh-key.yml
        when: new_user_generate_ssh_key | default('yes') | bool

      - include_tasks: configure-profile-picture.yml
        when: new_user_profile_picture_path !='' or new_user_random_profile_picture|bool
      #end block
      when:
        - new_user_created is defined
        - not new_user_created.failed
    # end block
    when: not (new_user_username_already_in_use|default('no'))
  #end block
  when:
    - new_user_username is defined
    - new_user_username != ""

- debug:
    msg: "No 'new_user_username' was defined"
  when: new_user_username is not defined or new_user_username == ""
