---
- name: Verify '/usr/local/bin' is present
  stat:
    path: /usr/local/bin
  register: usr_local_bin

- name: Verify '/usr/local/sbin' is present
  stat:
    path: /usr/local/sbin
  register: usr_local_sbin

- name: Add '/usr/local/bin' and '/usr/local/sbin' to '$PATH'
  lineinfile:
    path: "/Users/{{ new_user_username }}/{{ item.config_file }}"
    state: present
    regexp: '^.*/usr/local/s?bin.*$'
    insertafter: EOF
    line: "{{ item.line }}"
    create: yes
    owner: "{{ new_user_username }}"
    group: 'staff'
    mode: '0755'
  loop:
    - shell: 'bash'
      config_file: "/.bashrc"
      line: "export PATH={{ '/usr/local/bin:' if usr_local_bin.stat.isdir|bool else omit }}{{ '/usr/local/sbin:' if usr_local_sbin.stat.isdir|bool else omit  }}$PATH" # noqa 204

    - shell: 'zsh'
      config_file: "/.zshrc"
      line: "export PATH={{ '/usr/local/bin:' if usr_local_bin.stat.isdir|bool else omit }}{{ '/usr/local/sbin:' if usr_local_sbin.stat.isdir|bool else omit  }}$PATH" # noqa 204

    - shell: 'fish'
      config_file: ".config/fish/config.fish"
      line: "set -gx PATH {{ '/usr/local/bin' if usr_local_bin.stat.isdir|bool else omit }} {{ '/usr/local/sbin' if usr_local_sbin.stat.isdir|bool else omit  }} $PATH" # noqa 204
  when:
    - (usr_local_bin.stat.isdir is defined and usr_local_bin.stat.isdir) or (usr_local_sbin.stat.isdir is defined and usr_local_sbin.stat.isdir)
    - new_user_update_path_for_all_shell_types|bool or item.shell == new_user_shell
  become: "{{ new_user_username != ansible_user_id }}"
  become_user: "{{ new_user_username }}"
